### ISSUE TITLE
filter_variants not working if get_variants_as_tuples is called before

### ISSUE THREAD

**Issue by TNathusius** [process-intelligence-solutions/pm4py#235]
get_variants_as_tuples() sets pm4py.util.variants_util.VARIANT_SPECIFICATION to pm4py.util.variants_util.VariantsSpecifications.LIST from pm4py.util.variants_util.VariantsSpecifications.STRING

As a consequence, get_variants_df() (which is called in variants_filter.apply() in filter_variants()) will return variants as tuples.

However, the parameter admitted_variants of variants_filter.apply() is prepared so that the variant is one string in which activities are separated by a comma.

Thus, admitted_variants cannot be matched with the output of get_variants_df() and all cases are filtered from the event log.

This issue can be avoided by using get_variants() instead of get_variants_as_tuples(), but this throws a warning that get_variants() is deprecated.

**Comment by fit-alessandro-berti** [comment]
Dear TNathusius,

Thanks for signaling the issue!

We will correct this in our next release

**Comment by fit-alessandro-berti** [comment]
Dear TNathusius,

The issue has been solved in the current release

**Comment by goto-loop** [comment]
Hi @fit-alessandro-berti, I believe this issue still (or again) exists in the current 2.2.30 release. Code to reproduce:

```python
import pm4py

log = pm4py.read_xes('tests/input_data/running-example.xes')
# Uncomment next line to see the issue
# variants = pm4py.get_variants_as_tuples(log)
variants = {('register request', 'examine casually', 'check ticket', 'decide', 'reinitiate request', 'examine thoroughly', 'check ticket', 'decide', 'pay compensation'): 42}
for variant in variants:
    filtered_log = pm4py.filter_variants(log, [list(variant)])
    print(len(filtered_log))
    break
```

If you run the snippet like this, it will correctly print `1`, but if you uncomment line 5, it will print `0`.

**Comment by fit-alessandro-berti** [comment]
Dear @goto-loop try with     filtered_log = pm4py.filter_variants(log, [variant])

This works for both variant specifications and 2.3.0 release. It expects a tuple as member of the list. Not a list

**Comment by goto-loop** [comment]
You are right, this way it works – thanks for pointing out the wrong input type!

The function's [docstring comment](https://github.com/pm4py/pm4py-core/blob/release/pm4py/filtering.py#L252) says `A variant should be specified as a list of activity names, e.g., ['a','b','c']` so I assumed the conversion from tuple to list was necessary.

**Comment by fit-alessandro-berti** [comment]
Thanks for signaling! We corrected the issue in the documentation of filter_variants in the upcoming release 2.3.0
