### ISSUE TITLE
log_to_feature returns unexpected features when extracting follows relations

### ISSUE THREAD

**Issue by fmannhardt** [process-intelligence-solutions/pm4py#293]
I was refactoring my code to use the new method `log_to_feature` instead of the old deprecated variant of it.
Now the following code returns more than just the 2grams or directly follow relations:

```
sepsis = pd.read_csv("sepsis.csv", sep=';')
sepsis_log = pm4py.format_dataframe(sepsis, case_id='case_id', activity_key='activity', timestamp_key='timestamp')
sepsis_log = pm4py.convert_to_event_log(sepsis_log)
data_2gram, feature_names = log_to_features.apply(sepsis_log, parameters={"str_ev_attr": None, 
                                                        "str_tr_attr": None, 
                                                        "num_ev_attr": None, 
                                                        "num_tr_attr": None, 
                                                        "str_evsucc_attr": ["concept:name"]})
```

The list of features is:
```
['event:lifecycle@complete',
 'event:concept:name@Admission IC',
 'event:concept:name@Admission NC',
 'event:concept:name@CRP',
 'event:concept:name@ER Registration',
 'event:concept:name@ER Sepsis Triage',
 'event:concept:name@ER Triage',
 'event:concept:name@IV Antibiotics',
 'event:concept:name@IV Liquid',
 'event:concept:name@LacticAcid',
 'event:concept:name@Leucocytes',
 'event:concept:name@Release A',
 'event:concept:name@Release B',
 'event:concept:name@Release C',
 'event:concept:name@Release D',
 'event:concept:name@Release E',
 'event:concept:name@Return ER',
 'event:diagnosticurinarysediment',
 'event:sirscriteria2ormore',
 'event:diagnosticblood',
 'event:lacticacid',
 'event:leucocytes',
 'event:diagnosticartastrup',
 'event:age',
 'event:crp',
 'event:.order',
 'event:diagnosticic',
 'event:diagnosticlacticacid',
 'event:disfuncorg',
 'event:diagnosticurinaryculture',
 'event:infusion',
 'event:activity_instance_id',
 'event:hypotensie',
 'event:@@index',
 'event:sirscrittemperature',
 'event:sirscrittachypnea',
 'event:diagnosticxthorax',
 'event:sirscritheartrate',
 'event:diagnose',
 'event:infectionsuspected',
 'event:diagnosticecg',
 'succession:concept:name@Admission IC#Admission IC',
 'succession:concept:name@Admission IC#Admission NC',
 'succession:concept:name@Admission IC#CRP',
 'succession:concept:name@Admission IC#ER Sepsis Triage',
 'succession:concept:name@Admission IC#LacticAcid',
 'succession:concept:name@Admission IC#Leucocytes',
 'succession:concept:name@Admission NC#Admission IC',
 'succession:concept:name@Admission NC#Admission NC',
 'succession:concept:name@Admission NC#CRP',
 'succession:concept:name@Admission NC#ER Sepsis Triage',
 'succession:concept:name@Admission NC#ER Triage',
 'succession:concept:name@Admission NC#IV Antibiotics',
 'succession:concept:name@Admission NC#IV Liquid',
 'succession:concept:name@Admission NC#LacticAcid',
 'succession:concept:name@Admission NC#Leucocytes',
 'succession:concept:name@Admission NC#Release A',
 'succession:concept:name@Admission NC#Release B',
 'succession:concept:name@Admission NC#Release C',
 'succession:concept:name@Admission NC#Release D',
 'succession:concept:name@CRP#Admission IC',
 'succession:concept:name@CRP#Admission NC',
 'succession:concept:name@CRP#CRP',
 'succession:concept:name@CRP#ER Registration',
 'succession:concept:name@CRP#ER Sepsis Triage',
 'succession:concept:name@CRP#ER Triage',
 'succession:concept:name@CRP#IV Antibiotics',
 'succession:concept:name@CRP#IV Liquid',
 'succession:concept:name@CRP#LacticAcid',
 'succession:concept:name@CRP#Leucocytes',
 'succession:concept:name@CRP#Release A',
 'succession:concept:name@CRP#Release B',
 'succession:concept:name@CRP#Release C',
 'succession:concept:name@CRP#Release D',
 'succession:concept:name@CRP#Release E',
 'succession:concept:name@ER Registration#Admission IC',
 'succession:concept:name@ER Registration#CRP',
 'succession:concept:name@ER Registration#ER Sepsis Triage',
 'succession:concept:name@ER Registration#ER Triage',
 'succession:concept:name@ER Registration#IV Liquid',
 'succession:concept:name@ER Registration#LacticAcid',
 'succession:concept:name@ER Registration#Leucocytes',
 'succession:concept:name@ER Sepsis Triage#Admission IC',
 'succession:concept:name@ER Sepsis Triage#Admission NC',
 'succession:concept:name@ER Sepsis Triage#CRP',
 'succession:concept:name@ER Sepsis Triage#ER Registration',
 'succession:concept:name@ER Sepsis Triage#ER Triage',
 'succession:concept:name@ER Sepsis Triage#IV Antibiotics',
 'succession:concept:name@ER Sepsis Triage#IV Liquid',
 'succession:concept:name@ER Sepsis Triage#LacticAcid',
 'succession:concept:name@ER Sepsis Triage#Leucocytes',
 'succession:concept:name@ER Triage#CRP',
 'succession:concept:name@ER Triage#ER Registration',
 'succession:concept:name@ER Triage#ER Sepsis Triage',
 'succession:concept:name@ER Triage#IV Antibiotics',
 'succession:concept:name@ER Triage#IV Liquid',
 'succession:concept:name@ER Triage#LacticAcid',
 'succession:concept:name@ER Triage#Leucocytes',
 'succession:concept:name@IV Antibiotics#Admission IC',
 'succession:concept:name@IV Antibiotics#Admission NC',
 'succession:concept:name@IV Antibiotics#CRP',
 'succession:concept:name@IV Antibiotics#ER Registration',
 'succession:concept:name@IV Antibiotics#ER Triage',
 'succession:concept:name@IV Antibiotics#IV Liquid',
 'succession:concept:name@IV Antibiotics#LacticAcid',
 'succession:concept:name@IV Antibiotics#Leucocytes',
 'succession:concept:name@IV Antibiotics#Release A',
 'succession:concept:name@IV Antibiotics#Release B',
 'succession:concept:name@IV Liquid#Admission IC',
 'succession:concept:name@IV Liquid#Admission NC',
 'succession:concept:name@IV Liquid#CRP',
 'succession:concept:name@IV Liquid#ER Registration',
 'succession:concept:name@IV Liquid#ER Sepsis Triage',
 'succession:concept:name@IV Liquid#ER Triage',
 'succession:concept:name@IV Liquid#IV Antibiotics',
 'succession:concept:name@IV Liquid#LacticAcid',
 'succession:concept:name@IV Liquid#Leucocytes',
 'succession:concept:name@IV Liquid#Release A',
 'succession:concept:name@IV Liquid#Release B',
 'succession:concept:name@LacticAcid#Admission IC',
 'succession:concept:name@LacticAcid#Admission NC',
 'succession:concept:name@LacticAcid#CRP',
 'succession:concept:name@LacticAcid#ER Registration',
 'succession:concept:name@LacticAcid#ER Sepsis Triage',
 'succession:concept:name@LacticAcid#ER Triage',
 'succession:concept:name@LacticAcid#IV Antibiotics',
 'succession:concept:name@LacticAcid#IV Liquid',
 'succession:concept:name@LacticAcid#LacticAcid',
 'succession:concept:name@LacticAcid#Leucocytes',
 'succession:concept:name@LacticAcid#Release A',
 'succession:concept:name@LacticAcid#Release B',
 'succession:concept:name@LacticAcid#Release E',
 'succession:concept:name@Leucocytes#Admission IC',
 'succession:concept:name@Leucocytes#Admission NC',
 'succession:concept:name@Leucocytes#CRP',
 'succession:concept:name@Leucocytes#ER Registration',
 'succession:concept:name@Leucocytes#ER Sepsis Triage',
 'succession:concept:name@Leucocytes#ER Triage',
 'succession:concept:name@Leucocytes#IV Antibiotics',
 'succession:concept:name@Leucocytes#IV Liquid',
 'succession:concept:name@Leucocytes#LacticAcid',
 'succession:concept:name@Leucocytes#Leucocytes',
 'succession:concept:name@Leucocytes#Release A',
 'succession:concept:name@Leucocytes#Release B',
 'succession:concept:name@Leucocytes#Release C',
 'succession:concept:name@Leucocytes#Release D',
 'succession:concept:name@Leucocytes#Release E',
 'succession:concept:name@Leucocytes#Return ER',
 'succession:concept:name@Release A#CRP',
 'succession:concept:name@Release A#Leucocytes',
 'succession:concept:name@Release A#Return ER',
 'succession:concept:name@Release B#Admission NC',
 'succession:concept:name@Release C#Return ER',
 'succession:concept:name@Release D#Return ER',
 'succession:concept:name@Release E#Return ER',
 'succession:concept:name@Return ER#CRP']
```

Expected result would be:

```
[ 'succession:concept:name@Admission IC#Admission IC',
 'succession:concept:name@Admission IC#Admission NC',
 'succession:concept:name@Admission IC#CRP',
 'succession:concept:name@Admission IC#ER Sepsis Triage',
 'succession:concept:name@Admission IC#LacticAcid',
 'succession:concept:name@Admission IC#Leucocytes',
 'succession:concept:name@Admission NC#Admission IC',
 'succession:concept:name@Admission NC#Admission NC',
 'succession:concept:name@Admission NC#CRP',
 'succession:concept:name@Admission NC#ER Sepsis Triage',
 'succession:concept:name@Admission NC#ER Triage',
 'succession:concept:name@Admission NC#IV Antibiotics',
 'succession:concept:name@Admission NC#IV Liquid',
 'succession:concept:name@Admission NC#LacticAcid',
 'succession:concept:name@Admission NC#Leucocytes',
 'succession:concept:name@Admission NC#Release A',
 'succession:concept:name@Admission NC#Release B',
 'succession:concept:name@Admission NC#Release C',
 'succession:concept:name@Admission NC#Release D',
 'succession:concept:name@CRP#Admission IC',
 'succession:concept:name@CRP#Admission NC',
 'succession:concept:name@CRP#CRP',
 'succession:concept:name@CRP#ER Registration',
 'succession:concept:name@CRP#ER Sepsis Triage',
 'succession:concept:name@CRP#ER Triage',
 'succession:concept:name@CRP#IV Antibiotics',
 'succession:concept:name@CRP#IV Liquid',
 'succession:concept:name@CRP#LacticAcid',
 'succession:concept:name@CRP#Leucocytes',
 'succession:concept:name@CRP#Release A',
 'succession:concept:name@CRP#Release B',
 'succession:concept:name@CRP#Release C',
 'succession:concept:name@CRP#Release D',
 'succession:concept:name@CRP#Release E',
 'succession:concept:name@ER Registration#Admission IC',
 'succession:concept:name@ER Registration#CRP',
 'succession:concept:name@ER Registration#ER Sepsis Triage',
 'succession:concept:name@ER Registration#ER Triage',
 'succession:concept:name@ER Registration#IV Liquid',
 'succession:concept:name@ER Registration#LacticAcid',
 'succession:concept:name@ER Registration#Leucocytes',
 'succession:concept:name@ER Sepsis Triage#Admission IC',
 'succession:concept:name@ER Sepsis Triage#Admission NC',
 'succession:concept:name@ER Sepsis Triage#CRP',
 'succession:concept:name@ER Sepsis Triage#ER Registration',
 'succession:concept:name@ER Sepsis Triage#ER Triage',
 'succession:concept:name@ER Sepsis Triage#IV Antibiotics',
 'succession:concept:name@ER Sepsis Triage#IV Liquid',
 'succession:concept:name@ER Sepsis Triage#LacticAcid',
 'succession:concept:name@ER Sepsis Triage#Leucocytes',
 'succession:concept:name@ER Triage#CRP',
 'succession:concept:name@ER Triage#ER Registration',
 'succession:concept:name@ER Triage#ER Sepsis Triage',
 'succession:concept:name@ER Triage#IV Antibiotics',
 'succession:concept:name@ER Triage#IV Liquid',
 'succession:concept:name@ER Triage#LacticAcid',
 'succession:concept:name@ER Triage#Leucocytes',
 'succession:concept:name@IV Antibiotics#Admission IC',
 'succession:concept:name@IV Antibiotics#Admission NC',
 'succession:concept:name@IV Antibiotics#CRP',
 'succession:concept:name@IV Antibiotics#ER Registration',
 'succession:concept:name@IV Antibiotics#ER Triage',
 'succession:concept:name@IV Antibiotics#IV Liquid',
 'succession:concept:name@IV Antibiotics#LacticAcid',
 'succession:concept:name@IV Antibiotics#Leucocytes',
 'succession:concept:name@IV Antibiotics#Release A',
 'succession:concept:name@IV Antibiotics#Release B',
 'succession:concept:name@IV Liquid#Admission IC',
 'succession:concept:name@IV Liquid#Admission NC',
 'succession:concept:name@IV Liquid#CRP',
 'succession:concept:name@IV Liquid#ER Registration',
 'succession:concept:name@IV Liquid#ER Sepsis Triage',
 'succession:concept:name@IV Liquid#ER Triage',
 'succession:concept:name@IV Liquid#IV Antibiotics',
 'succession:concept:name@IV Liquid#LacticAcid',
 'succession:concept:name@IV Liquid#Leucocytes',
 'succession:concept:name@IV Liquid#Release A',
 'succession:concept:name@IV Liquid#Release B',
 'succession:concept:name@LacticAcid#Admission IC',
 'succession:concept:name@LacticAcid#Admission NC',
 'succession:concept:name@LacticAcid#CRP',
 'succession:concept:name@LacticAcid#ER Registration',
 'succession:concept:name@LacticAcid#ER Sepsis Triage',
 'succession:concept:name@LacticAcid#ER Triage',
 'succession:concept:name@LacticAcid#IV Antibiotics',
 'succession:concept:name@LacticAcid#IV Liquid',
 'succession:concept:name@LacticAcid#LacticAcid',
 'succession:concept:name@LacticAcid#Leucocytes',
 'succession:concept:name@LacticAcid#Release A',
 'succession:concept:name@LacticAcid#Release B',
 'succession:concept:name@LacticAcid#Release E',
 'succession:concept:name@Leucocytes#Admission IC',
 'succession:concept:name@Leucocytes#Admission NC',
 'succession:concept:name@Leucocytes#CRP',
 'succession:concept:name@Leucocytes#ER Registration',
 'succession:concept:name@Leucocytes#ER Sepsis Triage',
 'succession:concept:name@Leucocytes#ER Triage',
 'succession:concept:name@Leucocytes#IV Antibiotics',
 'succession:concept:name@Leucocytes#IV Liquid',
 'succession:concept:name@Leucocytes#LacticAcid',
 'succession:concept:name@Leucocytes#Leucocytes',
 'succession:concept:name@Leucocytes#Release A',
 'succession:concept:name@Leucocytes#Release B',
 'succession:concept:name@Leucocytes#Release C',
 'succession:concept:name@Leucocytes#Release D',
 'succession:concept:name@Leucocytes#Release E',
 'succession:concept:name@Leucocytes#Return ER',
 'succession:concept:name@Release A#CRP',
 'succession:concept:name@Release A#Leucocytes',
 'succession:concept:name@Release A#Return ER',
 'succession:concept:name@Release B#Admission NC',
 'succession:concept:name@Release C#Return ER',
 'succession:concept:name@Release D#Return ER',
 'succession:concept:name@Release E#Return ER',
 'succession:concept:name@Return ER#CRP']
```

I am using PM4Py v2.2.16

Here is the file I am using:
[sepsis.csv](https://github.com/pm4py/pm4py-core/files/7684863/sepsis.csv)
.

**Comment by fit-alessandro-berti** [comment]
Dear Felix,

We will propose a fix for this in one of the upcoming releases.

The problem currently is that if no attribute is provided for neither the string/numeric event/trace attributes, then a default selection is applied for these attributes.

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is fixed in https://github.com/pm4py/pm4py-core/releases/tag/2.2.17

**Comment by fmannhardt** [comment]
I am trying the same call again in PM4Py 2.2.30 and I am afraid it is still not fully fixed. I am getting the following response:

```
['event:concept:name@Admission IC',
 'event:concept:name@Admission NC',
 'event:concept:name@CRP',
 'event:concept:name@ER Registration',
 'event:concept:name@ER Sepsis Triage',
 'event:concept:name@ER Triage',
 'event:concept:name@IV Antibiotics',
 'event:concept:name@IV Liquid',
 'event:concept:name@LacticAcid',
 'event:concept:name@Leucocytes',
 'event:concept:name@Release A',
 'event:concept:name@Release B',
 'event:concept:name@Release C',
 'event:concept:name@Release D',
 'event:concept:name@Release E',
 'event:concept:name@Return ER',
 'event:Age',
 'succession:concept:name@Admission IC#Admission IC',
 'succession:concept:name@Admission IC#Admission NC',
 'succession:concept:name@Admission IC#CRP',
 'succession:concept:name@Admission IC#ER Sepsis Triage',
 'succession:concept:name@Admission IC#LacticAcid',
 'succession:concept:name@Admission IC#Leucocytes',
 'succession:concept:name@Admission NC#Admission IC',
 'succession:concept:name@Admission NC#Admission NC',
 'succession:concept:name@Admission NC#CRP',
 'succession:concept:name@Admission NC#ER Sepsis Triage',
 'succession:concept:name@Admission NC#ER Triage',
 'succession:concept:name@Admission NC#IV Antibiotics',
 'succession:concept:name@Admission NC#IV Liquid',
 'succession:concept:name@Admission NC#LacticAcid',
 'succession:concept:name@Admission NC#Leucocytes',
 'succession:concept:name@Admission NC#Release A',
 'succession:concept:name@Admission NC#Release B',
 'succession:concept:name@Admission NC#Release C',
 'succession:concept:name@Admission NC#Release D',
 'succession:concept:name@CRP#Admission IC',
 'succession:concept:name@CRP#Admission NC',
 'succession:concept:name@CRP#CRP',
 'succession:concept:name@CRP#ER Registration',
 'succession:concept:name@CRP#ER Sepsis Triage',
 'succession:concept:name@CRP#ER Triage',
 'succession:concept:name@CRP#IV Antibiotics',
 'succession:concept:name@CRP#IV Liquid',
 'succession:concept:name@CRP#LacticAcid',
 'succession:concept:name@CRP#Leucocytes',
 'succession:concept:name@CRP#Release A',
 'succession:concept:name@CRP#Release B',
 'succession:concept:name@CRP#Release C',
 'succession:concept:name@CRP#Release D',
 'succession:concept:name@CRP#Release E',
 'succession:concept:name@ER Registration#Admission IC',
 'succession:concept:name@ER Registration#CRP',
 'succession:concept:name@ER Registration#ER Sepsis Triage',
 'succession:concept:name@ER Registration#ER Triage',
 'succession:concept:name@ER Registration#IV Liquid',
 'succession:concept:name@ER Registration#LacticAcid',
 'succession:concept:name@ER Registration#Leucocytes',
 'succession:concept:name@ER Sepsis Triage#Admission IC',
 'succession:concept:name@ER Sepsis Triage#Admission NC',
 'succession:concept:name@ER Sepsis Triage#CRP',
 'succession:concept:name@ER Sepsis Triage#ER Registration',
 'succession:concept:name@ER Sepsis Triage#ER Triage',
 'succession:concept:name@ER Sepsis Triage#IV Antibiotics',
 'succession:concept:name@ER Sepsis Triage#IV Liquid',
 'succession:concept:name@ER Sepsis Triage#LacticAcid',
 'succession:concept:name@ER Sepsis Triage#Leucocytes',
 'succession:concept:name@ER Triage#CRP',
 'succession:concept:name@ER Triage#ER Registration',
 'succession:concept:name@ER Triage#ER Sepsis Triage',
 'succession:concept:name@ER Triage#IV Antibiotics',
 'succession:concept:name@ER Triage#IV Liquid',
 'succession:concept:name@ER Triage#LacticAcid',
 'succession:concept:name@ER Triage#Leucocytes',
 'succession:concept:name@IV Antibiotics#Admission IC',
 'succession:concept:name@IV Antibiotics#Admission NC',
 'succession:concept:name@IV Antibiotics#CRP',
 'succession:concept:name@IV Antibiotics#ER Registration',
 'succession:concept:name@IV Antibiotics#ER Triage',
 'succession:concept:name@IV Antibiotics#IV Liquid',
 'succession:concept:name@IV Antibiotics#LacticAcid',
 'succession:concept:name@IV Antibiotics#Leucocytes',
 'succession:concept:name@IV Antibiotics#Release A',
 'succession:concept:name@IV Antibiotics#Release B',
 'succession:concept:name@IV Liquid#Admission IC',
 'succession:concept:name@IV Liquid#Admission NC',
 'succession:concept:name@IV Liquid#CRP',
 'succession:concept:name@IV Liquid#ER Registration',
 'succession:concept:name@IV Liquid#ER Sepsis Triage',
 'succession:concept:name@IV Liquid#ER Triage',
 'succession:concept:name@IV Liquid#IV Antibiotics',
 'succession:concept:name@IV Liquid#LacticAcid',
 'succession:concept:name@IV Liquid#Leucocytes',
 'succession:concept:name@IV Liquid#Release A',
 'succession:concept:name@IV Liquid#Release B',
 'succession:concept:name@LacticAcid#Admission IC',
 'succession:concept:name@LacticAcid#Admission NC',
 'succession:concept:name@LacticAcid#CRP',
 'succession:concept:name@LacticAcid#ER Registration',
 'succession:concept:name@LacticAcid#ER Sepsis Triage',
 'succession:concept:name@LacticAcid#ER Triage',
 'succession:concept:name@LacticAcid#IV Antibiotics',
 'succession:concept:name@LacticAcid#IV Liquid',
 'succession:concept:name@LacticAcid#LacticAcid',
 'succession:concept:name@LacticAcid#Leucocytes',
 'succession:concept:name@LacticAcid#Release A',
 'succession:concept:name@LacticAcid#Release B',
 'succession:concept:name@LacticAcid#Release E',
 'succession:concept:name@Leucocytes#Admission IC',
 'succession:concept:name@Leucocytes#Admission NC',
 'succession:concept:name@Leucocytes#CRP',
 'succession:concept:name@Leucocytes#ER Registration',
 'succession:concept:name@Leucocytes#ER Sepsis Triage',
 'succession:concept:name@Leucocytes#ER Triage',
 'succession:concept:name@Leucocytes#IV Antibiotics',
 'succession:concept:name@Leucocytes#IV Liquid',
 'succession:concept:name@Leucocytes#LacticAcid',
 'succession:concept:name@Leucocytes#Leucocytes',
 'succession:concept:name@Leucocytes#Release A',
 'succession:concept:name@Leucocytes#Release B',
 'succession:concept:name@Leucocytes#Release C',
 'succession:concept:name@Leucocytes#Release D',
 'succession:concept:name@Leucocytes#Release E',
 'succession:concept:name@Leucocytes#Return ER',
 'succession:concept:name@Release A#CRP',
 'succession:concept:name@Release A#Leucocytes',
 'succession:concept:name@Release A#Return ER',
 'succession:concept:name@Release B#Admission NC',
 'succession:concept:name@Release C#Return ER',
 'succession:concept:name@Release D#Return ER',
 'succession:concept:name@Release E#Return ER',
 'succession:concept:name@Return ER#CRP']
```

For a call with:
```
data_2gram, feature_names = log_to_features.apply(sepsis_log, parameters={"str_ev_attr": None, 
                                                        "str_tr_attr": None, 
                                                        "num_ev_attr": None, 
                                                        "num_tr_attr": None, 
                                                        "str_evsucc_attr": ["concept:name"]})
```

Same file as used above.

**Comment by fit-alessandro-berti** [comment]
Dear Felix,

This behavior is triggered when you provide None to all the four different type of features (str_ev_attr, str_tr_attr, num_ev_attr, num_tr_attr). In that case, the algorithm assumes no feature is manually provided and proceed to automatic detection.

Try to provide empty lists instead of None for all the voices and only the successions should be returned then.

**Comment by fmannhardt** [comment]
I provided None only to the first four arguments, the last argument `str_evsucc_attr` was provided with a value. 
The workaround with empty lists instead of None works. Still, very confusing behavior.
