### ISSUE TITLE
There is a bug in the connection of heu_net for heuristic miner ++

### ISSUE THREAD

**Issue by JackEnzo** [process-intelligence-solutions/pm4py#356]
```import pm4py
from pm4py.algo.discovery.heuristics.variants import plusplus
from pm4py.visualization.heuristics_net import visualizer
from pm4py.visualization.petri_net import visualizer as pn_visualizer
import pandas as pd

def execute_script():
    df = pd.read_csv("../tests/input_data/interval_event_log.csv")
    df = pm4py.format_dataframe(df)
    heu_net_2 = plusplus.apply_heu_pandas(df, parameters={"heu_net_decoration": "frequency",  "min_dfg_occurrences": 142})
    gviz2 = visualizer.apply(heu_net_2, parameters={"format": "svg"})
    visualizer.view(gviz2)

    
if __name__ == "__main__":
    execute_script()
```

**Comment by fit-alessandro-berti** [comment]
Dear @CHINA-JACK-01 

Thanks for signaling. We will fix this issue in the next release.

**Comment by JackEnzo** [comment]
Thanks! I will always support pm4py! @fit-alessandro-berti

**Comment by fit-alessandro-berti** [comment]
we fixed the issue in pm4py 2.3.2

**Comment by JackEnzo** [comment]
Hi,@fit-alessandro-berti, the "min_dfg_occurrences" bug are still in the 2.3.2.
![connection_bug](https://user-images.githubusercontent.com/54665296/205534101-32f61427-14b8-4b17-8d75-9878b85a5707.svg)

**Comment by fit-alessandro-berti** [comment]
Dear @JackEnzo according to the specified example (filtering on DFG occurrences >= 142) that is the correct result.

You can also try with other values (1, 500, ...). For example, with 500:

![image](https://user-images.githubusercontent.com/56342194/205565884-b47bd3cf-9fac-4b37-9797-316eb62bee29.png)

Why the problem is not solved in your opinion?

**Comment by JackEnzo** [comment]
Dear @fit-alessandro-berti, I personally think that no matter how the filter conditions change, “heu_net” should ensure that all nodes have ingoing and outgoing edges. Is it possible to try to remove filtered edges or nodes from the source “df” to generate a more elegant graph？

**Comment by fit-alessandro-berti** [comment]
No, that was not granted by the algorithm or possible yet ;) We'll work towards providing a "connected activities" parameter in future for the heuristics miner variants.

But this is unconnected to the scope of the original issue

**Comment by JackEnzo** [comment]
thank you for your reply
